name=input("Enter ur name")
city=input("enter ur city")
fav_food= input("Enter ur fav food")
fav_cricket=input("enter ur fav cricket")
fav_actor=input("enter ur fav actor")
fav_author=input("enter ur fav author")
fav_sports=input("enter ur fav sports")
fav_book=input("enter ur fav book")
fav_song=input("enter ur fav song")
fav_country=input("enter ur fav country")
print("!!!!info!!!!")
print=(f'{name=}')
print=(f'{city=}')
print=(f'{fav_food=}')
print=(f'{fav_cricket=}')
print=(f'{fav_actor=}')
print=(f'{fav_author=}')
print=(f'{fav_sports=}')
print=(f'{fav_book=}')
print=(f'{fav_song=}')
print=(f'{fav_country=}')
